spring-cloud-gateway-configuration
taragrammatonn/notification-service pull request #20
Opened 2024-11-18 12:27 UTC by jah3

2024-11-20 08:54 UTC, taragrammatonn commented on gateway-notification-service/src/main/java/md/maib/gatewaynotificationservice/config/RoutesConfig.java
> +    public RouterFunction<ServerResponse>  notificationRouteService(){
you can also add this in application yml file, but still ok

2024-11-20 08:55 UTC, taragrammatonn approved these changes

2024-11-20 08:56 UTC, taragrammatonn commented
add some test

2024-11-20 13:29 UTC, taragrammatonn commented on gateway-notification-service/src/test/java/md/maib/gatewaynotificationservice/config/RoutesConfigTest.java
> +        assertThat(bean).isNotNull();
It's a just null check, need to test if your request pass getaway and return some valid result

2024-11-20 13:30 UTC, taragrammatonn requested changes
Pls add some request example with response assert

2024-11-23 10:45 UTC, taragrammatonn approved these changes
Fix comments before merge

2024-11-23 10:45 UTC, taragrammatonn commented on gateway-notification-service/pom.xml
> +            <artifactId>spring-boot-test</artifactId>
Redundant is case of starter test

2024-11-23 10:45 UTC, taragrammatonn commented on gateway-notification-service/pom.xml
> +            <artifactId>spring-boot-test</artifactId>
Twice the same dependency

2024-11-23 10:46 UTC, jah3 commented on gateway-notification-service/pom.xml
> +            <artifactId>spring-boot-test</artifactId>
Sure 👍🏽

2024-11-25 07:07 UTC, merged