update docker-compose
taragrammatonn/notification-service pull request #8
Opened 2024-11-08 09:50 UTC by jah3

2024-11-08 11:47 UTC, taragrammatonn requested changes

2024-11-08 11:47 UTC, taragrammatonn commented on docker-compose.yaml
> +  email-service:
This should be done by Mihail

2024-11-08 12:16 UTC, jah3 commented on docker-compose.yaml
> +  email-service:
You mean email service docker?

2024-11-08 18:38 UTC, taragrammatonn commented on docker-compose.yaml
> +  email-service:
all related email service thigs

2024-11-11 08:48 UTC, taragrammatonn requested changes

2024-11-11 08:56 UTC, jah3 commented on docker-compose.yaml
> +volumes:
kinda, it ensures that after several operations the data wouldn't be lost

2024-11-11 12:14 UTC, taragrammatonn commented
pls edit commit message

2024-11-11 12:26 UTC, closed without merging